import CustomerTemplate from "@/components/customerTemplates";
import MenuList from "../menuList";

export const metadata = {
    title: 'RailWay | Schedule',
    description: 'Generated by create next app',
};

type PropsLayout = {
    children: React.ReactNode;
};

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CustomerTemplate title="RailWay" id="schedule" menuList={MenuList}>
            {children}
        </CustomerTemplate>
    )
}

export default RootLayout;